// Apache-2.0. Derived from Agent Guild by AgentTanuki; see LICENSE.txt and PROVENANCE.md.

// Generated by ../tools/build-verifier.mjs from sdk/agentguild_verify.mjs at 9cf6c561468e60afb77acdbddebfc5134a155e4f.

// Only the current Data Integrity verification path is retained. Function bodies are unchanged.

const { createPublicKey, verify: edVerify, createHash: _createHash } = require('node:crypto');

const B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

function b58decode(s) {
  let n = 0n;
  for (const ch of s) {
    const i = B58.indexOf(ch);
    if (i < 0) throw new Error("bad base58");
    n = n * 58n + BigInt(i);
  }
  let hex = n.toString(16);
  if (hex.length % 2) hex = "0" + hex;
  let bytes = hex === "0" ? [] : [...Buffer.from(hex, "hex")];
  for (const ch of s) { if (ch === "1") bytes.unshift(0); else break; }
  return Buffer.from(bytes);
}

function publicKeyFromDid(did) {
  const mb = did.startsWith("did:key:") ? did.slice(8) : did;
  if (!mb.startsWith("z")) throw new Error("unsupported did multibase");
  const raw = b58decode(mb.slice(1));
  if (raw[0] !== 0xed || raw[1] !== 0x01) throw new Error("did:key is not Ed25519");
  return raw.subarray(2); // 32-byte raw Ed25519 public key
}

function edKey(raw32) {
  // Wrap the raw key in an SPKI DER so node:crypto can use it.
  const der = Buffer.concat([Buffer.from("302a300506032b6570032100", "hex"), raw32]);
  return createPublicKey({ key: der, format: "der", type: "spki" });
}

// Language-agnostic canonical JSON (AGI-1): sorted keys, no whitespace, ECMAScript
// number formatting. JSON.stringify already formats numbers the ECMAScript way
// (an integer-valued number has no decimal point), so a value the Python issuer
// canonicalised as "0" we also produce as "0".
function canon(v) {
  if (v === null) return "null";
  if (Array.isArray(v)) return "[" + v.map(canon).join(",") + "]";
  const t = typeof v;
  if (t === "object") {
    return "{" + Object.keys(v).sort()
      .map((k) => JSON.stringify(k) + ":" + canon(v[k])).join(",") + "}";
  }
  if (t === "number") {
    if (!Number.isFinite(v)) throw new Error("NaN/Infinity not permitted");
    return JSON.stringify(v);
  }
  return JSON.stringify(v); // string | boolean
}

function multibaseB58Decode(s) {
  if (!s.startsWith("z")) throw new Error("not base58btc multibase");
  return b58decode(s.slice(1));
}

// Conforming W3C Data Integrity, cryptosuite eddsa-jcs-2022
// (https://www.w3.org/TR/vc-di-eddsa/#eddsa-jcs-2022): JCS canonicalisation,
// hashData = SHA256(JCS(proofConfig)) || SHA256(JCS(document)), Ed25519,
// base58btc-multibase proofValue.
function verifyDataIntegrity(vc) {
  const proof = vc.proof || {};
  if (proof.cryptosuite !== "eddsa-jcs-2022" || !proof.proofValue) return false;
  const { proofValue, ...proofConfig } = proof;
  const { proof: _omit, ...document } = vc;
  if ("@context" in proofConfig
      && canon(proofConfig["@context"]) !== canon(document["@context"] ?? null)) return false;
  const vm = proof.verificationMethod || "";
  const did = vm ? vm.split("#", 1)[0] : (vc.issuer || "");
  if (vc.issuer && did !== vc.issuer) return false;
  const { createHash } = awaitlessCrypto();
  const hashData = Buffer.concat([
    createHash("sha256").update(Buffer.from(canon(proofConfig), "utf8")).digest(),
    createHash("sha256").update(Buffer.from(canon(document), "utf8")).digest(),
  ]);
  try {
    return edVerify(null, hashData, edKey(publicKeyFromDid(did)),
                    multibaseB58Decode(proofValue));
  } catch { return false; }
}

function awaitlessCrypto() { return { createHash: _createHash }; }

module.exports = { verifyDataIntegrity, publicKeyFromDid, canon };

